version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zadanie
      MYSQL_USER: zadanie_user
      MYSQL_PASSWORD: 123haslo456
    ports:
      - "3307:3307"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: zadanie_user 
      PMA_PASSWORD: 123haslo456
    ports:
      - "8081:80"
    depends_on:
      - db
